name: Update GTFS Data and View

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-gtfs:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-codeql: "true"
          remove-haskell: "true"
          remove-docker-images: "true"

      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v1
      - run: |
          export PUPPETEER_SKIP_DOWNLOAD=true
          bun install
          sudo apt-get update && sudo apt-get install -y libzip-dev libbz2-dev pbzip2 lz4

      - name: CIS
        run: bun cis:run

      - name: Feeds
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: bun feeds:run

      - name: Cleanup CIS
        run: rm -rf .tmp/cp-sk

      - name: Checkout gtfs branch
        run: |
          rm -rf gtfs-branch

          git clone --branch gtfs --single-branch https://github.com/${{ github.repository }}.git gtfs-branch --depth 1

          mkdir -p .tmp/previous-gtfs
          cp -r gtfs-branch/gtfs/* .tmp/previous-gtfs

      - name: Install OSM data
        run: |
          mkdir -p .tmp/morph/osm
          curl -L https://de1-transiq.xhyrom.dev/slovakia-2025-08-13.osm.lz4 -o .tmp/morph/osm/latest.osm.lz4
          lz4 -d .tmp/morph/osm/latest.osm.lz4 .tmp/morph/osm/latest.osm
          rm .tmp/morph/osm/latest.osm.lz4

      - name: Morph
        run: |
          export TMPDIR=.tmp
          bun morph:run --jobs=1

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Copy and commit GTFS files
        run: |
          cd gtfs-branch

          cp -r ../gtfs .

          git add -A
          git commit -m "ðŸ“¦ Update GTFS data $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gtfs

  update-view:
    runs-on: ubuntu-latest
    needs: [update-gtfs]

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "24"
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - run: |
          bun install

          cd gtfs-view
          bun install

          go install github.com/public-transport/gtfsclean@latest

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Checkout gtfs branch
        run: |
          rm -rf gtfs-branch

          git clone --branch gtfs --single-branch https://github.com/${{ github.repository }}.git gtfs-branch

      - name: GTFS View
        run: |
          cp -r gtfs-branch/gtfs gtfs
          NODE_OPTIONS=--max_old_space_size=8000 node gtfs-view/index.mjs

      - name: Kaeru web
        run: bun kaeru:web

      - name: Copy and commit GTFS files
        run: |
          cd gtfs-branch

          rm -rf view || true
          mkdir -p view

          cp -r ../.tmp/build/gtfs-view/* view/

          rm -rf kaeru || true
          mkdir -p kaeru

          cp -r ../.tmp/build/kaeru/* kaeru/

          git add -A
          git commit -m "ðŸ‘€ Update View for GTFS data $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gtfs
